# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"imprimir": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://v-ibarra.github.io/nbdev_2/"

git_url = "https://github.com/v-ibarra/nbdev_2/tree/master/"

def custom_doc_links(name): return None
